[book]
authors = ["The Funkin' Crew Inc.", "EliteMasterEric"]
language = "en"
multilingual = false
src = "src"
title = "Friday Night Funkin' Modding Documentation"


[output.html]
git-repository-url = "https://github.com/FunkinCrew/funkin-modding-docs/tree/main/"
edit-url-template = "https://github.com/FunkinCrew/funkin-modding-docs/edit/main/{path}"
